-- add to cart
--remove from cart
--login register logout
--search by name 
--filter by size || name
--add to fav
-- create product 
--edit product
--remove product
-- don't duplicate items in cart
-- product details
